name: github action 실행해보기
on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World찍기
        run: echo "hello world"

      - name: 여러문장
        run: |
          echo "good"
          echo "bye"

      - name: 깃허브변수
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 깃액션 secret
        run: |
          echo ${{ secrets.MY_NAME }}
