name: github action 실행해보기
on:
  push:
    branches:
      - main

jobs:
  My-deploy-Job:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/ubuntu/2025action

    steps:
      - name: ssh to ec2
        uses: appleboy.ssh/action@v.1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            git pull
            npm ci
            npm run build
